version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "bin/**",
    "grafana/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/linkers/linkerd2"]
