# used in docker-compose configurations

global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'conduit-controller'
    static_configs:
    - targets:
      - 'destination:9999'
      - 'prometheus:9090'
      - 'proxy-api:9996'
      - 'public-api:9995'
      - 'tap:9998'
      - 'telemetry:9997'
      - 'web:9994'
    relabel_configs:
    - action: labelmap
      regex: __address__
      replacement: component
    - action: replace
      source_labels: [component]
      regex: ^(.*):.*$
      target_label: component

  - job_name: 'conduit-proxy'
    static_configs:
    - targets:
      - 'simulate-proxy:9000'
      - 'simulate-proxy:9001'
      - 'simulate-proxy:9002'
