---
dist: trusty
sudo: false

# We do not test pushes to branches, since they are redundant with the pull_request build
# for each branch. Take that, Big CI!
branches:
  only:
    - master

stages:
  - name: docker-deploy

jobs:
  include:
    - language: generic

      before_install:
        - docker version

      before_script:
        - |
          export CONDUIT_TAG=$(. bin/_tag.sh ; clean_head_root_tag)
          echo "CONDUIT_TAG=${CONDUIT_TAG}"
        - export BUILD_DEBUG=1 DOCKER_TRACE=1

      script:
        - bin/docker-build-controller

    - language: generic

      before_install:
        - docker version

      before_script:
        - |
          export CONDUIT_TAG=$(. bin/_tag.sh ; clean_head_root_tag)
          echo "CONDUIT_TAG=${CONDUIT_TAG}"
        - export BUILD_DEBUG=1 DOCKER_TRACE=1

      script:
        - bin/docker-build-web

    - language: generic

      before_install:
        - docker version

      before_script:
        - |
          export CONDUIT_TAG=$(. bin/_tag.sh ; clean_head_root_tag)
          echo "CONDUIT_TAG=${CONDUIT_TAG}"
        - export BUILD_DEBUG=1 DOCKER_TRACE=1

      script:
        # Proxy tests are run in the `test` stage, re-running them here would be
        # redundant/slow. #280
        - bin/docker-build-proxy-init

    - language: generic

      before_install:
        - docker version

      before_script:
        - |
          export CONDUIT_TAG=$(. bin/_tag.sh ; clean_head_root_tag)
          echo "CONDUIT_TAG=${CONDUIT_TAG}"
        - export BUILD_DEBUG=1 DOCKER_TRACE=1

      script:
        - bin/docker-build-cli

    - language: generic

      before_install:
        - docker version

      before_script:
        - |
          export CONDUIT_TAG=$(. bin/_tag.sh ; clean_head_root_tag)
          echo "CONDUIT_TAG=${CONDUIT_TAG}"
        - export BUILD_DEBUG=1 DOCKER_TRACE=1

      script:
        - bin/docker-build-proxy

notifications:
  email:
    on_success: never
