# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  azureSubscriptionEndpoint: 'azure-resource-manager-connection'

stages:
- stage: Build_and_run
  displayName: Build and run
  jobs:
  - job: Go_lint
    displayName: Go lint
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: gcr.io/linkerd-io/go-deps:7ac58ac0
    steps:
    - checkout: self
      path: linkerd2-checkout
      # path: go/src/github.com/linkerd/linkerd2
      fetchDepth: 1
    - script: $(Build.SourcesDirectory)/test-infra/go-lint.sh
      env:
        GOPATH: $(Pipeline.Workspace)/go
  - job: Go_tests
    displayName: Go tests
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: gcr.io/linkerd-io/go-deps:7ac58ac0
    steps:
    - checkout: self
      path: linkerd2-checkout
      # path: go/src/github.com/linkerd/linkerd2
      fetchDepth: 1
    - script: $(Build.SourcesDirectory)/test-infra/go-tests.sh
      env:
        GOPATH: $(Pipeline.Workspace)/go
  - job: JS_tests
    displayName: JS tests
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: node:10.16.0-stretch
    steps:
    - checkout: self
      path: go/src/github.com/linkerd/linkerd2
      fetchDepth: 1
    - script: $(Build.SourcesDirectory)/test-infra/js-tests.sh
  - job: Integration_tests
    displayName: Integration tests
    pool:
      name: Default
    container:
      image: gcr.io/linkerd-io/l5d-builder:latest
      options: --privileged
    steps:
    - checkout: self
      path: linkerd2-checkout
      # path: go/src/github.com/linkerd/linkerd2
      fetchDepth: 1
    - script: $(Build.SourcesDirectory)/test-infra/integration-tests-pipelines.sh
      env:
        GOPATH: $(Pipeline.Workspace)/go
