[workspace]
members = [
  "proxy",
  "proxy/convert",
  "proxy/controller-grpc",
  "proxy/futures-mpsc-lossy",
  "proxy/router",
]

[patch.crates-io]
prost-derive = { git = "https://github.com/danburkert/prost" }

[patch."https://github.com/bluejekyll/trust-dns"]
trust-dns-resolver = { git = "https://github.com/hawkw/trust-dns", branch = "eliza/async-resolver-api-improvement" }
