[workspace]
members = [
  "proxy",
  "proxy/convert",
  "proxy/controller-grpc",
  "proxy/futures-mpsc-lossy",
  "proxy/router",
]

[patch.crates-io]
h2 = { git = "https://github.com/carllerche/h2" }
mio = { git = "https://github.com/carllerche/mio" }
