required = ["github.com/golang/protobuf/protoc-gen-go"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b" # cobra has no release tags at time of writing

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.9.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/pkg/browser"
  revision = "c90ca0c84f15f81c982e32665bffd8d7aac8f097" # browser has no release tags at time of writing

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845" # protobuf has no release tags at time of writing

#
# k8s.io/kubernetes dependency fixes
# taken from https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json
#

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
	name = "github.com/russross/blackfriday"
	revision = "300106c228d52c8941d4b3de6054a6062a86dda3"
