{{with .Values -}}
---
###
### Heartbeat
###
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: heartbeat
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  schedule: "{{.HeartbeatSchedule}}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{.ControllerComponentLabel}}: heartbeat
          annotations:
            {{.CreatedByAnnotation}}: {{.CliVersion}}
        spec:
          serviceAccountName: linkerd-heartbeat
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: {{.ControllerImage}}
            imagePullPolicy: {{.ImagePullPolicy}}
            args:
            - "heartbeat"
            - "-prometheus-url=http://linkerd-prometheus.{{.Namespace}}.svc.cluster.local:9090"
            - "-controller-namespace={{.Namespace}}"
            - "-log-level={{.ControllerLogLevel}}"
            {{- include "resources" .HeartbeatResources | nindent 12 }}
            securityContext:
              runAsUser: {{.ControllerUID}}
{{end -}}
