{{with .Values -}}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{.Namespace}}
  {{- if .ProxyAutoInjectEnabled }}
  annotations:
    {{.ProxyInjectAnnotation}}: {{.ProxyInjectDisabled}}
  {{- end }}
{{end -}}
