{{with .Values -}}
---
###
### Control Plane PSP
###
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: linkerd-{{.Namespace}}-control-plane
spec:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  {{- if not .NoInitContainer }}
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  {{- end}}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-psp
  namespace: {{.Namespace}}
rules:
- apiGroups: ['policy', 'extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - linkerd-{{.Namespace}}-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-psp
  namespace: {{.Namespace}}
roleRef:
  kind: Role
  name: linkerd-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-controller
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-grafana
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-identity
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-prometheus
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-proxy-injector
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-sp-validator
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.Namespace}}
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Namespace}}
{{end -}}
