{{with .Values -}}
---
###
### Tap
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-tap
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: tap
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: tap
  ports:
  - name: grpc
    port: 8088
    targetPort: 8088
  - name: apiserver
    port: 443
    targetPort: apiserver
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: linkerd-tap
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: tap
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  replicas: {{.ControllerReplicas}}
  template:
    metadata:
      labels:
        {{.ControllerComponentLabel}}: tap
      annotations:
        {{.CreatedByAnnotation}}: {{.CliVersion}}
    spec:
      serviceAccountName: linkerd-tap
      containers:
      - name: tap
        ports:
        - name: grpc
          containerPort: 8088
        - name: apiserver
          containerPort: 8089
        - name: admin-http
          containerPort: 9998
        volumeMounts:
        - name: tls
          mountPath: /var/run/linkerd/tls
          readOnly: true
        image: {{.ControllerImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
        - "tap"
        - "-controller-namespace={{.Namespace}}"
        - "-log-level={{.ControllerLogLevel}}"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9998
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9998
          failureThreshold: 7
        {{- include "resources" .TapResources | nindent 8 }}
        securityContext:
          runAsUser: {{.ControllerUID}}
      volumes:
      - name: tls
        secret:
          secretName: linkerd-tap-tls
      {{- if .HighAvailability }}
      {{- $local := dict "Label" .ControllerComponentLabel "Component" "tap" }}
      {{- include "pod-affinity" $local | nindent 6 }}
      {{- end }}
{{end -}}
