{{with .Values -}}
{{- if empty .Configs -}}
{{- fail ".Configs must be defined and non-empty" -}}
{{- end -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: controller
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
data:
  global: |
    {{- toJson (required ".Configs.Global must be non-empty" .Configs.Global) | nindent 4 }}
  proxy: |
    {{- toJson (required ".Configs.Proxy must be non-empty" .Configs.Proxy) | nindent 4 }}
  install: |
  {{- if .Configs.Install -}}
    {{- toJson .Configs.Install | nindent 4 }}
  {{ else }}
    {"uuid":"{{ uuidv4  }}","cliVersion":"{{.LinkerdVersion}}", "flags":[]}
  {{- end -}}
{{- end -}}
