{{with .Values -}}
---
###
### Heartbeat
###
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: heartbeat
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
spec:
  schedule: "{{.HeartbeatSchedule}}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{.ControllerComponentLabel}}: heartbeat
          annotations:
            {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
        spec:
          serviceAccountName: linkerd-heartbeat
          restartPolicy: OnFailure
          containers:
          - name: heartbeat
            image: {{.ControllerImage}}:{{default $.Chart.AppVersion .ControllerImageVersion}}
            imagePullPolicy: {{.ImagePullPolicy}}
            args:
            - "heartbeat"
            - "-prometheus-url=http://linkerd-prometheus.{{.Namespace}}.svc.{{.ClusterDomain}}:9090"
            - "-controller-namespace={{.Namespace}}"
            - "-log-level={{.ControllerLogLevel}}"
            image: {{.ControllerImage}}:{{default $.Chart.AppVersion .ControllerImageVersion}}
            imagePullPolicy: {{.ImagePullPolicy}}
            {{- if eq .HighAvailability true -}}
            {{- include "partials.resources" .HeartbeatResources | nindent 12 }}
            {{- end }}
            securityContext:
              runAsUser: {{.ControllerUID}}
{{- end -}}
