{{with .Values -}}
---
###
### Proxy Injector
###
---
{{ if empty .Proxy.Image.Version -}}
{{ $_ := set .Proxy.Image "Version" $.Chart.AppVersion -}}
{{ end -}}
{{ $_ := set .Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Proxy "Component" "linkerd-proxy-injector" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
  labels:
    {{.ControllerComponentLabel}}: proxy-injector
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  name: linkerd-proxy-injector
  namespace: {{.Namespace}}
spec:
  replicas: {{ternary .ControllerReplicas 1 (eq .HighAvailability true)}}
  selector:
    matchLabels:
      {{.ControllerComponentLabel}}: proxy-injector
      {{.ControllerNamespaceLabel}}: {{.Namespace}}
      {{- include "partials.proxy.labels" .Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .Proxy| nindent 8}}
      labels:
        {{.ControllerComponentLabel}}: proxy-injector
        {{.ControllerNamespaceLabel}}: {{.Namespace}}
        {{- include "partials.proxy.labels" .Proxy | nindent 8}}
    spec:
      {{- if eq .HighAvailability true -}}
      {{- $local := dict "Component" "proxy-injector" "Label" .ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - proxy-injector
        - -log-level={{.ControllerLogLevel}}
        image: {{.ControllerImage}}:{{default $.Chart.AppVersion .ControllerImageVersion}}
        imagePullPolicy: {{.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: proxy-injector
        ports:
        - containerPort: 8443
          name: proxy-injector
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if eq .HighAvailability true -}}
        {{- include "partials.resources" .ProxyInjectorResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
      {{- include "partials.proxy" .Proxy | nindent 6 -}}
      initContainers:
      {{- include "partials.proxy-init" .ProxyInit | nindent 6 }}
      serviceAccountName: linkerd-proxy-injector
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - name: tls
        secret:
          secretName: linkerd-proxy-injector-tls
      {{- include "partials.proxy.volumes.identity" . | nindent 6 }}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-proxy-injector
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: proxy-injector
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: proxy-injector
  ports:
  - name: proxy-injector
    port: 443
    targetPort: proxy-injector
{{- end -}}
