version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true
    # environment:
    # - GOCACHE: "/tmp/go/cache"
    # docker: # run the steps with Docker
    # - image: circleci/golang:1.12.6
    working_directory: /home/circleci/.go_workspace/src/github.com/linkerd/linkerd2
    steps:
    # - setup_remote_docker:
    #     docker_layer_caching: true
    - checkout
    - run:
        name: Install Go
        command: |
          wget -O $HOME/go1.12.6.linux-amd64.tar.gz https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf $HOME/go1.12.6.linux-amd64.tar.gz
    - run:
        name: Install kubectl
        command: |
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.3/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
    - run:
        name: Install kind
        command: |
          curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/
    - run:
        name: Create Kubernetes Cluster
        command: |
          export ROOT_TAG=$(bin/root-tag)
          kind create cluster --name $ROOT_TAG
          export KUBECONFIG="$(kind get kubeconfig-path --name $ROOT_TAG)"
          kubectl cluster-info
          kubectl get ns
    - run:
        name: Build Docker images
        command: |
          DOCKER_TRACE=1 bin/docker-build
    - run:
        name: Run Integration Tests
        command: |
          export ROOT_TAG=$(bin/root-tag)
          export KUBECONFIG="$(kind get kubeconfig-path --name $ROOT_TAG)"
          export LINKERD_BIN=`pwd`/bin/linkerd
          export VERSION="$($LINKERD_BIN version --client --short | tr -cd '[:alnum:]-')"
          export NAMESPACE=l5d-integration-kind-$VERSION

          docker pull buoyantio/bb:v0.0.5
          kind load docker-image --name $ROOT_TAG buoyantio/bb:v0.0.5

          docker pull gcr.io/linkerd-io/proxy-init:v1.0.0
          kind load docker-image --name $ROOT_TAG gcr.io/linkerd-io/proxy-init:v1.0.0

          docker pull prom/prometheus:v2.7.1
          kind load docker-image --name $ROOT_TAG prom/prometheus:v2.7.1

          kind load docker-image --name $ROOT_TAG gcr.io/linkerd-io/controller:$VERSION
          kind load docker-image --name $ROOT_TAG gcr.io/linkerd-io/grafana:$VERSION
          kind load docker-image --name $ROOT_TAG gcr.io/linkerd-io/proxy:$VERSION
          kind load docker-image --name $ROOT_TAG gcr.io/linkerd-io/web:$VERSION

          bin/dep ensure -vendor-only -v
          bin/dep status -v

          bin/test-run $LINKERD_BIN $NAMESPACE
    - run:
        name: Cleanup
        command: |
          export ROOT_TAG=$(bin/root-tag)
          kind delete cluster --name $ROOT_TAG
