{{ if .Values.grafana.enabled -}}
---
###
### Grafana RBAC
###
kind: ServiceAccount
apiVersion: v1
metadata:
  name: grafana
  namespace: {{.Values.namespace}}
  labels:
    {{.Values.extensionAnnotation}}: viz
    component: grafana
    namespace: {{.Values.namespace}}
{{- include "partials.image-pull-secrets" .Values.imagePullSecrets }}
{{ end -}}
