---
apiVersion: v1
kind: Namespace
metadata:
  name: l5d-builder
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: l5d-builder
  namespace: l5d-builder
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: l5d-builder
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: l5d-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: l5d-builder
subjects:
- kind: ServiceAccount
  name: l5d-builder
  namespace: l5d-builder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l5d-builder
  namespace: l5d-builder
spec:
  selector:
    matchLabels:
      app: l5d-builder
  template:
    metadata:
      labels:
        app: l5d-builder
    spec:
      serviceAccount: l5d-builder
      containers:
      - image: gcr.io/linkerd-io/l5d-builder:latest
        name: l5d-builder
        command:
        - "sleep"
        args:
        - "84600"
        env:
        - name: DOCKER_HOST
          value: tcp://dind.dind.svc.cluster.local:2375
      # - image: library/docker:18.09.6-dind
      #   name: dind
      #   env:
      #   - name: DOCKER_IN_DOCKER_ENABLED
      #     value: "true"
      #   securityContext:
      #     privileged: true
      #   volumeMounts:
      #   - name: dind-storage
      #     mountPath: /var/lib/docker
      #   - name: docker-graph
      #     mountPath: /docker-graph
      #   - name: modules
      #     mountPath: /lib/modules
      #     readOnly: true
      #   - name: cgroup
      #     mountPath: /sys/fs/cgroup
      # volumes:
      # - name: dind-storage
      #   emptyDir: {}
      # - name: docker-graph
      #   emptyDir:
      #     medium: "Memory"
      # - name: modules
      #   hostPath:
      #     path: /lib/modules
      #     type: Directory
      # - name: cgroup
      #   hostPath:
      #     path: /sys/fs/cgroup
      #     type: Directory
