---
apiVersion: v1
kind: Namespace
metadata:
  name: l5d-builder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l5d-builder
  namespace: l5d-builder
spec:
  selector:
    matchLabels:
      app: l5d-builder
  template:
    metadata:
      labels:
        app: l5d-builder
    spec:
      containers:
      - image: gcr.io/linkerd-io/l5d-builder:latest
        name: l5d-builder
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      - image: library/docker:18.09.6-dind
        name: dind
        env:
        - name: DOCKER_IN_DOCKER_ENABLED
          value: "true"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: docker-graph
          mountPath: /docker-graph
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: docker-graph
        emptyDir:
          medium: "Memory"
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
