apiVersion: v1
kind: Pod
metadata:
  annotations:
    prow.k8s.io/job: integration
  labels:
    created-by-prow: "true"
    event-GUID: none
    prow.k8s.io/id: 796d0cb3-fake
    prow.k8s.io/job: integration
    prow.k8s.io/refs.org: siggy
    prow.k8s.io/refs.pull: "4"
    prow.k8s.io/refs.repo: linkerd2
    prow.k8s.io/type: presubmit
  name: 796d0cb3-fake
  namespace: test-pods
  resourceVersion: "642148"
  selfLink: /api/v1/namespaces/test-pods/pods/796d0cb3-fake
spec:
  automountServiceAccountToken: true
  containers:
  - command:
    - /tools/entrypoint
    env:
    - name: DOCKER_HOST
      value: tcp://dind.dind.svc.cluster.local:2375
    - name: ARTIFACTS
      value: /logs/artifacts
    - name: BUILD_ID
      value: "1144037959540936704"
    - name: BUILD_NUMBER
      value: "1144037959540936704"
    - name: GOPATH
      value: /home/prow/go
    - name: JOB_NAME
      value: integration
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"integration","buildid":"1144037959540936704","prowjobid":"796d0cb3-fake","refs":{"org":"siggy","repo":"linkerd2","repo_link":"https://github.com/siggy/linkerd2","base_ref":"master","base_sha":"eb994eef3eefe39477073c29e8bcf6d0ab187468","base_link":"https://github.com/siggy/linkerd2/commit/eb994eef3eefe39477073c29e8bcf6d0ab187468","pulls":[{"number":4,"author":"siggy","sha":"34329cca38aa013210d23d9dd49f370c3105c53c","link":"https://github.com/siggy/linkerd2/pull/4","commit_link":"https://github.com/siggy/linkerd2/pull/4/commits/34329cca38aa013210d23d9dd49f370c3105c53c","author_link":"https://github.com/siggy"}]}}'
    - name: JOB_TYPE
      value: presubmit
    - name: PROW_JOB_ID
      value: 796d0cb3-fake
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: eb994eef3eefe39477073c29e8bcf6d0ab187468
    - name: PULL_NUMBER
      value: "4"
    - name: PULL_PULL_SHA
      value: 34329cca38aa013210d23d9dd49f370c3105c53c
    - name: PULL_REFS
      value: master:eb994eef3eefe39477073c29e8bcf6d0ab187468,4:34329cca38aa013210d23d9dd49f370c3105c53c
    - name: REPO_NAME
      value: linkerd2
    - name: REPO_OWNER
      value: siggy
    - name: ENTRYPOINT_OPTIONS
      value: '{"timeout":0,"grace_period":0,"artifact_dir":"/logs/artifacts","args":["sleep", "86400"],"process_log":"/logs/process-log.txt","marker_file":"/logs/marker-file.txt","metadata_file":"/logs/artifacts/metadata.json"}'
    image: gcr.io/linkerd-io/l5d-builder:latest
    imagePullPolicy: Always
    name: test
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /logs
      name: logs
    - mountPath: /tools
      name: tools
    - mountPath: /home/prow/go
      name: code
    workingDir: /home/prow/go/src/github.com/siggy/linkerd2
  - command:
    - /sidecar
    env:
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"integration","buildid":"1144037959540936704","prowjobid":"796d0cb3-fake","refs":{"org":"siggy","repo":"linkerd2","repo_link":"https://github.com/siggy/linkerd2","base_ref":"master","base_sha":"eb994eef3eefe39477073c29e8bcf6d0ab187468","base_link":"https://github.com/siggy/linkerd2/commit/eb994eef3eefe39477073c29e8bcf6d0ab187468","pulls":[{"number":4,"author":"siggy","sha":"34329cca38aa013210d23d9dd49f370c3105c53c","link":"https://github.com/siggy/linkerd2/pull/4","commit_link":"https://github.com/siggy/linkerd2/pull/4/commits/34329cca38aa013210d23d9dd49f370c3105c53c","author_link":"https://github.com/siggy"}]}}'
    - name: SIDECAR_OPTIONS
      value: '{"gcs_options":{"items":["/logs/artifacts"],"bucket":"prow-artifacts-linkerd","path_strategy":"explicit","gcs_credentials_file":"/secrets/gcs/service-account.json","dry_run":false},"entries":[{"args":["l5d-builder.sh"],"process_log":"/logs/process-log.txt","marker_file":"/logs/marker-file.txt","metadata_file":"/logs/artifacts/metadata.json"}]}'
    image: gcr.io/k8s-prow/sidecar:v20190622-591061040
    imagePullPolicy: IfNotPresent
    name: sidecar
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /logs
      name: logs
    - mountPath: /secrets/gcs
      name: gcs-credentials
  dnsPolicy: ClusterFirst
  initContainers:
  - command:
    - /clonerefs
    env:
    - name: CLONEREFS_OPTIONS
      value: '{"src_root":"/home/prow/go","log":"/logs/clone.json","git_user_name":"ci-robot","git_user_email":"ci-robot@k8s.io","refs":[{"org":"siggy","repo":"linkerd2","repo_link":"https://github.com/siggy/linkerd2","base_ref":"master","base_sha":"eb994eef3eefe39477073c29e8bcf6d0ab187468","base_link":"https://github.com/siggy/linkerd2/commit/eb994eef3eefe39477073c29e8bcf6d0ab187468","pulls":[{"number":4,"author":"siggy","sha":"34329cca38aa013210d23d9dd49f370c3105c53c","link":"https://github.com/siggy/linkerd2/pull/4","commit_link":"https://github.com/siggy/linkerd2/pull/4/commits/34329cca38aa013210d23d9dd49f370c3105c53c","author_link":"https://github.com/siggy"}]}]}'
    image: gcr.io/k8s-prow/clonerefs:v20190622-591061040
    imagePullPolicy: IfNotPresent
    name: clonerefs
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /logs
      name: logs
    - mountPath: /home/prow/go
      name: code
  - command:
    - /initupload
    env:
    - name: INITUPLOAD_OPTIONS
      value: '{"bucket":"prow-artifacts-linkerd","path_strategy":"explicit","gcs_credentials_file":"/secrets/gcs/service-account.json","dry_run":false,"log":"/logs/clone.json"}'
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"integration","buildid":"1144037959540936704","prowjobid":"796d0cb3-fake","refs":{"org":"siggy","repo":"linkerd2","repo_link":"https://github.com/siggy/linkerd2","base_ref":"master","base_sha":"eb994eef3eefe39477073c29e8bcf6d0ab187468","base_link":"https://github.com/siggy/linkerd2/commit/eb994eef3eefe39477073c29e8bcf6d0ab187468","pulls":[{"number":4,"author":"siggy","sha":"34329cca38aa013210d23d9dd49f370c3105c53c","link":"https://github.com/siggy/linkerd2/pull/4","commit_link":"https://github.com/siggy/linkerd2/pull/4/commits/34329cca38aa013210d23d9dd49f370c3105c53c","author_link":"https://github.com/siggy"}]}}'
    image: gcr.io/k8s-prow/initupload:v20190622-591061040
    imagePullPolicy: IfNotPresent
    name: initupload
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /logs
      name: logs
    - mountPath: /secrets/gcs
      name: gcs-credentials
  - args:
    - /entrypoint
    - /tools/entrypoint
    command:
    - /bin/cp
    image: gcr.io/k8s-prow/entrypoint:v20190622-591061040
    imagePullPolicy: IfNotPresent
    name: place-entrypoint
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tools
      name: tools
  nodeName: gke-prowtest-default-pool-5f6f7342-j947
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: l5d-builder
  serviceAccountName: l5d-builder
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: logs
  - emptyDir: {}
    name: tools
  - name: gcs-credentials
    secret:
      defaultMode: 420
      secretName: gcs-credentials
  - emptyDir: {}
    name: code
