# Default values for linkerd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterDomain: &cluster_domain cluster.local
CNIEnabled: &cni_enabled false # not supported in Linkerd 2.5
EnableH2Upgrade: true
HighAvailability: &high_availability false
ImagePullPolicy: &image_pull_policy IfNotPresent
LinkerdVersion: &linkerd_version stable-2.4.0
Namespace: &namespace linkerd
OmitWebhookSideEffects: &omit_webhook_side_effects false

# controller configuration
ControllerImage: gcr.io/linkerd-io/controller
ControllerLogLevel: &controller_log_level info
ControllerReplicas: 3
ControllerResources: &controller_resources
  CPU: &controller_resources_cpu
    Limit: "1"
    Request: 100m
  Memory: &controller_resources_memory
    Limit: 250Mi
    Request: 50Mi
ControllerUID: 2103
DestinationResources:
  <<: *controller_resources
PublicAPIResources:
  <<: *controller_resources

# identity configuration
Identity:
  Issuer:
    # PEM encoded certificate
    CrtPEM: &identity_issuer_crt |
      -----BEGIN CERTIFICATE-----
      MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
      eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwNzI2MDMxNjQ4WhcNMjAwNzI1
      MDMxNzA4WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
      YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwPFIAEAosip9WpovFw3MrJQ3W
      NqCzU54MXTMUEaNQBNcHyzz8xfZ2vZY56TQQod3HQ8dEcPwRNgTFJxgzdt03o0Iw
      QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
      MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJpWjlDgXGo8hgvr
      WX/H+QmI4sSA3EiW1J9ZNweS94UsAiB9IN9rkv/b47tYsynZCpLTzSeF7+16VdyI
      DT1weqC2Vg==
      -----END CERTIFICATE-----

    # Must match the expiry date in CrtPEM
    CrtExpiry: 2020-07-25T03:17:08Z
    CrtExpiryAnnotation: linkerd.io/identity-issuer-expiry

    # PEM encode ECDSA private key
    KeyPEM: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEINfi1j8CjonK4FCuDoCUPXRxVMNResGsQDbFqEXTUeJUoAoGCCqGSM49
      AwEHoUQDQgAE8DxSABAKLIqfVqaLxcNzKyUN1jags1OeDF0zFBGjUATXB8s8/MX2
      dr2WOek0EKHdx0PHRHD8ETYExScYM3bdNw==
      -----END EC PRIVATE KEY-----
  Resources:
    CPU:
      <<: *controller_resources_cpu
    Memory: *controller_resources_memory
  TrustDomain: *cluster_domain

# grafana configuration
GrafanaImage: gcr.io/linkerd-io/grafana
GrafanaResources:
  <<: *controller_resources

# heartbeat configuration
HeartbeatResources:
  <<: *controller_resources
HeartbeatSchedule: "0 0 * * * "

# prometheus configuration
PrometheusImage: prom/prometheus:v2.11.1
PrometheusLogLevel: *controller_log_level
PrometheusResources:
  <<: *controller_resources

# proxy configuration
Proxy:
  Capabilities:
    Add:
    Drop:
  ClusterDomain: *cluster_domain
  ControlPlaneNamespace: *namespace
  EnableExternalProfile: false
  HighAvailability: *high_availability
  Identity:
    TrustDomain: *cluster_domain
    TrustAnchors: *identity_issuer_crt
  Image:
    Name: &proxy_image_name gcr.io/linkerd-io/proxy
    PullPolicy: *image_pull_policy
    Version: *linkerd_version
  LogLevel: &proxy_log_level warn,linkerd2_proxy=info
  MountPaths:
  Port: &proxy_ports
    Admin: &proxy_port_admin 4191
    Control: &proxy_port_control 4190
    Inbound: &proxy_port_inbound 4143
    Outbound: &proxy_port_outbound 4140
  UID: &proxy_uid 2102

  # use this to override the default resource requirements in HA mode
  ResourceRequirements:
    CPU:
      Limit: &proxy_cpu_limit "1"
      Request: &proxy_cpu_request 100m
    Memory:
      Limit: &proxy_memory_limit 250Mi
      Request: &proxy_memory_request 20Mi

  # inject-only options. Do not change this for control plane installation
  DisableIdentity: false
  DisableTap: false

# proxy-init configuration
ProxyInit:
  Capabilities:
    Add:
    Drop:
  Image:
    Name: &proxy_init_image_name gcr.io/linkerd-io/proxy-init
    PullPolicy: *image_pull_policy
    Version: &proxy_init_image_version v1.0.0
  Proxy:
    Port:
      <<: *proxy_ports
      IgnoreInboundPorts: ""
      IgnoreOutboundPorts: "443"
    UID: *proxy_uid

  # use this to override the default resource requirements in HA mode
  ResourceRequirements:
    CPU:
      Limit: 100m
      Request: 10m
    Memory:
      Limit: 50Mi
      Request: 10Mi

# proxy injector configuration
ProxyInjectorResources:
  <<: *controller_resources

# service profile validator configuration
SPValidatorResources:
  <<: *controller_resources

# tap configuration
TapResources:
  <<: *controller_resources

# web configuration
WebImage: gcr.io/linkerd-io/web
WebResources:
  <<: *controller_resources

# linkerd-config config map data
Configs:
  Global:
    clusterDomain: *cluster_domain
    cniEnabled: *cni_enabled
    identityContext:
      trustAnchorsPem": *identity_issuer_crt
      trustDomain: *cluster_domain
    linkerdNamespace: *namespace
    omitWebhookSideEffects: *omit_webhook_side_effects
    version: *linkerd_version
  Proxy:
    adminPort:
      port: *proxy_port_admin
    controlPort:
      port: *proxy_port_control
    ignoreInboundPorts: []
    ignoreOutboundPorts: []
    inboundPort:
      port: *proxy_port_inbound
    logLevel:
      level: *proxy_log_level
    outboundPort:
      port: *proxy_port_outbound
    proxyImage:
      imageName: *proxy_image_name
      pullPolicy: *image_pull_policy
    proxyInitImage:
      imageName: *proxy_init_image_name
      pullPolicy: *image_pull_policy
    proxyInitImageVersion: *proxy_init_image_version
    proxyUid: *proxy_uid
    proxyVersion: *linkerd_version
    resource:
      limitCpu: *proxy_cpu_limit
      limitMemory: *proxy_memory_limit
      requestCpu: *proxy_cpu_request
      requestMemory: *proxy_memory_request
    disableExternalProfiles: true

# annotations
CreatedByAnnotation: linkerd.io/created-by
ProxyInjectAnnotation: linkerd.io/inject
ProxyInjectDisabled: disabled

# labels
ControllerComponentLabel: linkerd.io/control-plane-component
ControllerNamespaceLabel: linkerd.io/control-plane-ns
LinkerdNamespaceLabel: linkerd.io/is-control-plane
