# Default values for linkerd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterDomain: &cluster_domain cluster.local
EnableH2Upgrade: true
EnablePodAntiAffinity: false
ImagePullPolicy: &image_pull_policy IfNotPresent

# control plane version. See Proxy section for proxy version
LinkerdVersion: &linkerd_version stable-2.4.0

Namespace: linkerd
OmitWebhookSideEffects: false
WebhookFailurePolicy: Ignore

# controller configuration
ControllerImage: gcr.io/linkerd-io/controller
ControllerLogLevel: &controller_log_level info
ControllerReplicas: 1
ControllerUID: 2103

# identity configuration
Identity:
  Issuer:
    ClockSkewAllowance: 20s

    # PEM-encoded certificate
    CrtPEM: |
      -----BEGIN CERTIFICATE-----
      MIIBhDCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
      eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwNzI4MjMxODEzWhcNMjAwNzI3
      MjMxODMzWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
      YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASRnMzvjn+4MpDtsLEseoWlBzrF
      S0iGBVFLD0mYDbRzHDjCzwAvOA3y884B+UYysCOFS9E5O96Q7ftf3FySFGkHo0Iw
      QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
      MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAKG6GF0/tRTj9IWH
      3ntw1IpGD3uIxbJjWzl2nVDmqRawAiEAir+H+rVfGWL+UO8EiqtiRSm39hV7qA1g
      N1B+Z/vF63s=
      -----END CERTIFICATE-----

    # must match the expiry date in CrtPEM
    CrtExpiry: 2020-07-27T23:18:33Z

    # control plane annotation - do not edit
    CrtExpiryAnnotation: linkerd.io/identity-issuer-expiry

    IssuanceLifeTime: 86400s

    # PEM-encoded ECDSA private key
    KeyPEM: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIGTGK1a6wufBFXuugI9uQ6zQ77TUyMZOvu5DrzAZC++5oAoGCCqGSM49
      AwEHoUQDQgAEkZzM745/uDKQ7bCxLHqFpQc6xUtIhgVRSw9JmA20cxw4ws8ALzgN
      8vPOAflGMrAjhUvROTvekO37X9xckhRpBw==
      -----END EC PRIVATE KEY-----

  TrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBhDCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
    eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwNzI4MjMxODEzWhcNMjAwNzI3
    MjMxODMzWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
    YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASRnMzvjn+4MpDtsLEseoWlBzrF
    S0iGBVFLD0mYDbRzHDjCzwAvOA3y884B+UYysCOFS9E5O96Q7ftf3FySFGkHo0Iw
    QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAKG6GF0/tRTj9IWH
    3ntw1IpGD3uIxbJjWzl2nVDmqRawAiEAir+H+rVfGWL+UO8EiqtiRSm39hV7qA1g
    N1B+Z/vF63s=
    -----END CERTIFICATE-----

  TrustDomain: *cluster_domain

# grafana configuration
GrafanaImage: gcr.io/linkerd-io/grafana

# heartbeat configuration
HeartbeatSchedule: "0 0 * * * "

# prometheus configuration
PrometheusImage: prom/prometheus:v2.11.1
PrometheusLogLevel: *controller_log_level

# proxy configuration
Proxy:
  EnableExternalProfile: false
  Image:
    Name: gcr.io/linkerd-io/proxy
    PullPolicy: *image_pull_policy
    Version: *linkerd_version
  LogLevel: warn,linkerd2_proxy=info
  Ports:
    Admin: 4191
    Control: 4190
    Inbound: 4143
    Outbound: 4140
  Resources:
    CPU:
      Limit:
      Request:
    Memory:
      Limit:
      Request:
  UID: 2102

# proxy-init configuration
ProxyInit:
  IgnoreInboundPorts: ""
  IgnoreOutboundPorts: ""
  Image:
    Name: gcr.io/linkerd-io/proxy-init
    PullPolicy: *image_pull_policy
    Version: v1.0.0
  Resources:
    CPU:
      Limit: 100m
      Request: 10m
    Memory:
      Limit: 50Mi
      Request: 10Mi

# proxy injector configuration
#ProxyInjectorResources: *controller_resources

# service profile validator configuration
#SPValidatorResources: *controller_resources

# tap configuration
#TapResources: *controller_resources

# web configuration
WebImage: gcr.io/linkerd-io/web
#WebResources: *controller_resources

# control plane annotations - do not edit
CreatedByAnnotation: linkerd.io/created-by
ProxyInjectAnnotation: linkerd.io/inject
ProxyInjectDisabled: disabled

# control plane labels - do not edit
ControllerComponentLabel: linkerd.io/control-plane-component
ControllerNamespaceLabel: linkerd.io/control-plane-ns
LinkerdNamespaceLabel: linkerd.io/is-control-plane
