# Default values for linkerd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterDomain: &cluster_domain cluster.local
CNIEnabled: false # not supported in Linkerd 2.5
EnableH2Upgrade: true
HighAvailability: false
ImagePullPolicy: &image_pull_policy IfNotPresent
LinkerdVersion: &linkerd_version stable-2.4.0
Namespace: linkerd
OmitWebhookSideEffects: false

# controller configuration
ControllerImage: gcr.io/linkerd-io/controller
ControllerLogLevel: &controller_log_level info
ControllerReplicas: 3
ControllerResources: &controller_resources
  CPU: &controller_resources_cpu
    Limit: "1"
    Request: 100m
  Memory: &controller_resources_memory
    Limit: 250Mi
    Request: 50Mi
ControllerUID: 2103
DestinationResources:
  <<: *controller_resources
PublicAPIResources:
  <<: *controller_resources

# identity configuration
Identity:
  Issuer:
    ClockSkewAllowance: 20s

    # PEM encoded certificate
    CrtPEM: |
      -----BEGIN CERTIFICATE-----
      MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
      eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwNzI2MDMxNjQ4WhcNMjAwNzI1
      MDMxNzA4WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
      YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwPFIAEAosip9WpovFw3MrJQ3W
      NqCzU54MXTMUEaNQBNcHyzz8xfZ2vZY56TQQod3HQ8dEcPwRNgTFJxgzdt03o0Iw
      QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
      MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJpWjlDgXGo8hgvr
      WX/H+QmI4sSA3EiW1J9ZNweS94UsAiB9IN9rkv/b47tYsynZCpLTzSeF7+16VdyI
      DT1weqC2Vg==
      -----END CERTIFICATE-----

    # Must match the expiry date in CrtPEM
    CrtExpiry: 2020-07-25T03:17:08Z
    CrtExpiryAnnotation: linkerd.io/identity-issuer-expiry

    IssuanceLifeTime: 86400s

    # PEM encode ECDSA private key
    KeyPEM: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEINfi1j8CjonK4FCuDoCUPXRxVMNResGsQDbFqEXTUeJUoAoGCCqGSM49
      AwEHoUQDQgAE8DxSABAKLIqfVqaLxcNzKyUN1jags1OeDF0zFBGjUATXB8s8/MX2
      dr2WOek0EKHdx0PHRHD8ETYExScYM3bdNw==
      -----END EC PRIVATE KEY-----
  Resources:
    CPU:
      <<: *controller_resources_cpu
    Memory: *controller_resources_memory
  TrustDomain: *cluster_domain

# grafana configuration
GrafanaImage: gcr.io/linkerd-io/grafana
GrafanaResources:
  <<: *controller_resources

# heartbeat configuration
HeartbeatResources:
  <<: *controller_resources
HeartbeatSchedule: "0 0 * * * "

# prometheus configuration
PrometheusImage: prom/prometheus:v2.11.1
PrometheusLogLevel: *controller_log_level
PrometheusResources:
  <<: *controller_resources

# proxy configuration
Proxy:
  Capabilities:
    Add:
    Drop:
  EnableExternalProfile: false
  Image:
    Name: gcr.io/linkerd-io/proxy
    PullPolicy: *image_pull_policy
    Version: *linkerd_version
  LogLevel: warn,linkerd2_proxy=info
  MountPaths:
  Port:
    Admin: 4191
    Control: 4190
    Inbound: 4143
    Outbound: 4140
  UID: 2102

  # use this to override the default resource requirements in HA mode
  ResourceRequirements:
    CPU:
      Limit: "1"
      Request: 100m
    Memory:
      Limit: 250Mi
      Request: 20Mi

  # inject-only options. Do not change this for control plane installation
  DisableIdentity: false
  DisableTap: false

# proxy-init configuration
ProxyInit:
  Capabilities:
    Add:
    Drop:
  Image:
    Name: gcr.io/linkerd-io/proxy-init
    PullPolicy: *image_pull_policy
    Version: v1.0.0
  IgnoreInboundPorts: ""
  IgnoreOutboundPorts: "443"
  MountPath:

  # use this to override the default resource requirements in HA mode
  ResourceRequirements:
    CPU:
      Limit: 100m
      Request: 10m
    Memory:
      Limit: 50Mi
      Request: 10Mi

# proxy injector configuration
ProxyInjectorResources:
  <<: *controller_resources

# service profile validator configuration
SPValidatorResources:
  <<: *controller_resources

# tap configuration
TapResources:
  <<: *controller_resources

# web configuration
WebImage: gcr.io/linkerd-io/web
WebResources:
  <<: *controller_resources

# annotations
CreatedByAnnotation: linkerd.io/created-by
ProxyInjectAnnotation: linkerd.io/inject
ProxyInjectDisabled: disabled

# labels
ControllerComponentLabel: linkerd.io/control-plane-component
ControllerNamespaceLabel: linkerd.io/control-plane-ns
LinkerdNamespaceLabel: linkerd.io/is-control-plane
