---
###
### Controller
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-controller-api
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: controller
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.ControllerComponentLabel}}: controller
  ports:
  - name: http
    port: 8085
    targetPort: 8085
---
{{ $_ := set .Values.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Values.Proxy "Component" "linkerd-controller" -}}
{{ include "linkerd.proxy.validation" .Values.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
  labels:
    {{.Values.ControllerComponentLabel}}: controller
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  name: linkerd-controller
  namespace: {{.Values.Namespace}}
spec:
  replicas: {{.Values.ControllerReplicas}}
  selector:
    matchLabels:
      {{.Values.ControllerComponentLabel}}: controller
      {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
      {{- include "partials.proxy.labels" .Values.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
        {{- include "partials.proxy.annotations" .Values.Proxy| nindent 8}}
      labels:
        {{.Values.ControllerComponentLabel}}: controller
        {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
        {{- include "partials.proxy.labels" .Values.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .Values.EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "controller" "Label" .Values.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - public-api
        - -prometheus-url=http://linkerd-prometheus.{{.Values.Namespace}}.svc.{{.Values.ClusterDomain}}:9090
        - -destination-addr=linkerd-dst.{{.Values.Namespace}}.svc.{{.Values.ClusterDomain}}:8086
        - -controller-namespace={{.Values.Namespace}}
        - -log-level={{.Values.ControllerLogLevel}}
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.Values.ControllerImage}}:{{default .Values.LinkerdVersion .Values.ControllerImageVersion}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: public-api
        ports:
        - containerPort: 8085
          name: http
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if .Values.PublicAPIResources -}}
        {{- include "partials.resources" .Values.PublicAPIResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-controller
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
