---
###
### Grafana RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-grafana
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: grafana
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
