{{ if not .Values.DisableHeartBeat -}}
---
###
### Heartbeat
###
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: heartbeat
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
spec:
  schedule: "{{.Values.HeartbeatSchedule}}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{.Values.ControllerComponentLabel}}: heartbeat
          annotations:
            {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
        spec:
          {{- include "linkerd.node-selector" . | nindent 10 }}
          serviceAccountName: linkerd-heartbeat
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: {{.Values.ControllerImage}}:{{default .Values.LinkerdVersion .Values.ControllerImageVersion}}
            imagePullPolicy: {{.Values.ImagePullPolicy}}
            args:
            - "heartbeat"
            - "-prometheus-url=http://linkerd-prometheus.{{.Values.Namespace}}.svc.{{.Values.ClusterDomain}}:9090"
            - "-controller-namespace={{.Values.Namespace}}"
            - "-log-level={{.Values.ControllerLogLevel}}"
            {{- if .Values.HeartbeatResources -}}
            {{- include "partials.resources" .Values.HeartbeatResources | nindent 12 }}
            {{- end }}
            securityContext:
              runAsUser: {{.Values.ControllerUID}}
{{- end }}
