{{if .Values.Identity -}}
---
###
### Identity Controller Service RBAC
###
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.Namespace}}-identity
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.Namespace}}-identity
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Values.Namespace}}-identity
subjects:
- kind: ServiceAccount
  name: linkerd-identity
  namespace: {{.Values.Namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: identity
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
{{ end -}}
