{{- /*
  This config-map is used to store the configuration of add-ons, which is useful during upgrades.  
  As fields like global, etc are added by helm and we would not want them in the data, second level fields should be used 
  instead of directly specifying the add-on field.
*/ -}}
{{ if or (.Values.tracing.enabled) -}}
---
###
### linkerd values
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-values
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    tracing:
      enabled: {{.Values.tracing.enabled}}
      collector:
  {{- toYaml .Values.tracing.collector | trim | nindent 8}}
      jaeger:
  {{- toYaml .Values.tracing.jaeger | trim | nindent 8}}
{{ end -}}
