{{- if (.Values.installNamespace) -}}
---
###
### Linkerd Namespace
###
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    {{.Values.proxyInjectAnnotation}}: {{.Values.proxyInjectDisabled}}
  labels:
    {{.Values.linkerdNamespaceLabel}}: "true"
    config.linkerd.io/admission-webhooks: disabled
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
{{ end -}}
