{{- if (.Values.InstallNamespace) -}}
---
###
### Linkerd Namespace
###
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.Namespace }}
  annotations:
    {{.Values.ProxyInjectAnnotation}}: {{.Values.ProxyInjectDisabled}}
  labels:
    {{.Values.LinkerdNamespaceLabel}}: "true"
    config.linkerd.io/admission-webhooks: disabled
{{ end -}}
