---
###
### Prometheus RBAC
###
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.Namespace}}-prometheus
  labels:
    {{.Values.ControllerComponentLabel}}: prometheus
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.Namespace}}-prometheus
  labels:
    {{.Values.ControllerComponentLabel}}: prometheus
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Values.Namespace}}-prometheus
subjects:
- kind: ServiceAccount
  name: linkerd-prometheus
  namespace: {{.Values.Namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-prometheus
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: prometheus
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
