---
###
### Service Profile Validator
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-sp-validator
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: sp-validator
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.ControllerComponentLabel}}: sp-validator
  ports:
  - name: sp-validator
    port: 443
    targetPort: sp-validator
---
{{ $_ := set .Values.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Values.Proxy "Component" "linkerd-sp-validator" -}}
{{ include "linkerd.proxy.validation" .Values.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
  labels:
    {{.Values.ControllerComponentLabel}}: sp-validator
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  name: linkerd-sp-validator
  namespace: {{.Values.Namespace}}
spec:
  replicas: {{.Values.ControllerReplicas}}
  selector:
    matchLabels:
      {{.Values.ControllerComponentLabel}}: sp-validator
  template:
    metadata:
      annotations:
        {{- if empty .Values.CliVersion }}
        linkerd.io/helm-release-version: {{ $.Release.Revision | quote}}
        {{- end }}
        {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
        {{- include "partials.proxy.annotations" .Values.Proxy| nindent 8}}
      labels:
        {{.Values.ControllerComponentLabel}}: sp-validator
        {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
        {{- include "partials.proxy.labels" .Values.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .Values.EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "sp-validator" "Label" .Values.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - sp-validator
        - -log-level={{.Values.ControllerLogLevel}}
        image: {{.Values.ControllerImage}}:{{default .Values.LinkerdVersion .Values.ControllerImageVersion}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9997
          initialDelaySeconds: 10
        name: sp-validator
        ports:
        - containerPort: 8443
          name: sp-validator
        - containerPort: 9997
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9997
        {{- if .Values.SPValidatorResources -}}
        {{- include "partials.resources" .Values.SPValidatorResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-sp-validator
      volumes:
      - name: tls
        secret:
          secretName: linkerd-sp-validator-tls
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
