---
###
### TrafficSplit CRD
### Copied from https://github.com/deislabs/smi-sdk-go/blob/cea7e1e9372304bbb6c74a3f6ca788d9eaa9cc58/crds/split.yaml
###
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trafficsplits.split.smi-spec.io
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
spec:
  group: split.smi-spec.io
  scope: Namespaced
  names:
    kind: TrafficSplit
    listKind: TrafficSplitList
    shortNames:
      - ts
    plural: trafficsplits
    singular: trafficsplit
  version: v1alpha2
  versions:
    - name: v1alpha2
      served: true
      storage: true
    - name: v1alpha1
      served: false
      storage: false
  additionalPrinterColumns:
    - name: Service
      type: string
      description: The apex service of this split.
      JSONPath: .spec.service
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - service
            - backends
          properties:
            service:
              description: The apex service of this split.
              type: string
            backends:
              description: The backend services of this split.
              type: array
              items:
                type: object
                required: ['service', 'weight']
                properties:
                  service:
                    description: Name of the Kubernetes service.
                    type: string
                  weight:
                    description: Traffic weight value of this backend.
                    type: number
