---
###
### Web
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.ControllerComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
{{ $_ := set .Values.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Values.Proxy "Component" "linkerd-web" -}}
{{ include "linkerd.proxy.validation" .Values.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
  name: linkerd-web
  namespace: {{.Values.Namespace}}
spec:
  replicas: {{.Values.Dashboard.Replicas}}
  selector:
    matchLabels:
      {{.Values.ControllerComponentLabel}}: web
      {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
      {{- include "partials.proxy.labels" .Values.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.Values.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.LinkerdVersion) .Values.CliVersion}}
        {{- include "partials.proxy.annotations" .Values.Proxy| nindent 8}}
      labels:
        {{.Values.ControllerComponentLabel}}: web
        {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
        {{- include "partials.proxy.labels" .Values.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      containers:
      - args:
        - -api-addr=linkerd-controller-api.{{.Values.Namespace}}.svc.{{.Values.ClusterDomain}}:8085
        - -grafana-addr=linkerd-grafana.{{.Values.Namespace}}.svc.{{.Values.ClusterDomain}}:3000
        - -controller-namespace={{.Values.Namespace}}
        - -log-level={{.Values.ControllerLogLevel}}
        {{- $hostFull := replace "." "\\." (printf "linkerd-web.%s.svc.%s" .Values.Namespace .Values.ClusterDomain) }}
        {{- $hostAbbrev := replace "." "\\." (printf "linkerd-web.%s.svc" .Values.Namespace) }}
        - -enforced-host=^(localhost|127\.0\.0\.1|{{ $hostFull }}|{{ $hostAbbrev }}|\[::1\])(:\d+)?$
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.Values.WebImage}}:{{default .Values.LinkerdVersion .Values.ControllerImageVersion}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        name: web
        ports:
        - containerPort: 8084
          name: http
        - containerPort: 9994
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9994
        {{- if .Values.WebResources -}}
        {{- include "partials.resources" .Values.WebResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-web
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
