apiVersion: "v1"
appVersion: edge-19.8.2
description: Linkerd gives you observability, reliability, and security for your microservices — with no code change required.
home: https://linkerd.io
keywords:
- service-mesh
kubeVersion: ">=1.12.0-0"
name: "linkerd2"
sources:
- https://github.com/linkerd/linkerd2/
version: 0.1.0
