name: linkerd
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Command-line utility to interact with linkerd
description: |
    Linkerd is a service mesh, designed to give platform-wide observability,
    reliability, and security without requiring configuration or code changes.

grade: devel
confinement: devmode

parts:
    linkerd:
        plugin: dump
        source: .
        override-pull: |
            cd "$SNAPCRAFT_PART_SOURCE" # this line might be wrong. also maybe unneeded
            curl -sSLO https://github.com/linkerd/linkerd2/releases/download/edge-20.3.1/linkerd2-cli-edge-20.3.1-linux
            mv linkerd2-cli-edge-20.3.1-linux linkerd # rename binary to linkerd
            chmod +x linkerd
        build-packages:
            - curl
apps:
    linkerd:
        command: linkerd
