name: linkerd
base: core18
version: '2.7.0'
summary: Command-line utility to interact with linkerd
description: |
    Linkerd is a service mesh, designed to give platform-wide observability,
    reliability, and security without requiring configuration or code changes.

grade: stable
confinement: classic

parts:
    linkerd:
        plugin: dump
        source: .
        stage:
            - target/release/linkerd2-cli-*-linux
        override-stage: |
            snapcraftctl stage
            cp target/release/linkerd2-cli-*-linux $SNAPCRAFT_PRIME/linkerd
apps:
    linkerd:
        command: linkerd
