name: linkerd
base: core18
version: '2.7.0'
summary: Command-line utility to interact with linkerd
description: |
    Linkerd is a service mesh, designed to give platform-wide observability,
    reliability, and security without requiring configuration or code changes.

grade: stable
confinement: classic

parts:
    linkerd:
        plugin: dump
        source: .
        override-pull: |
            curl -sSLO https://github.com/linkerd/linkerd2/releases/download/stable-2.7.0/linkerd2-cli-stable-2.7.0-linux
            mv linkerd2-cli-stable-2.7.0-linux linkerd # rename binary to linkerd
            chmod +x linkerd
        build-packages:
            - curl
apps:
    linkerd:
        command: linkerd
