name: Static checks
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
jobs:
  go_dependencies:
    name: Go dependencies
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Dump env
      run: env | sort
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Validate go deps
      run: |
        . bin/_tag.sh
        for f in $( grep -lR --include=Dockerfile\* go-deps: . ) ; do
          validate_go_deps_tag $f
        done
  go_lint:
    name: Go lint
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.4
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Go lint
      env:
        GITCOOKIE_SH: ${{ secrets.GITCOOKIE_SH }}
      run: |
        echo "$GITCOOKIE_SH" | bash
        bin/lint --verbose
  go_format:
    name: Go format
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.4
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Format
      env:
        GITCOOKIE_SH: ${{ secrets.GITCOOKIE_SH }}
      run: |
        echo "$GITCOOKIE_SH" | bash
        bin/fmt
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: shellcheck
      # TODO: fix our shell scripts and re-enable checks
      run: |
        bin/shellcheck bin/* --exclude="\
        SC1036,\
        SC1061,\
        SC1062,\
        SC1072,\
        SC1073,\
        SC1081,\
        SC1088,\
        SC1090,\
        SC2001,\
        SC2005,\
        SC2013,\
        SC2027,\
        SC2034,\
        SC2039,\
        SC2046,\
        SC2048,\
        SC2064,\
        SC2068,\
        SC2086,\
        SC2089,\
        SC2090,\
        SC2116,\
        SC2120,\
        SC2124,\
        SC2155,\
        SC2175,\
        SC2119,\
        SC2148,\
        SC2154,\
        SC2215,\
        SC2220,\
        SC2236"
